In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [5]:
type(myarray)

numpy.ndarray

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [16]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [17]:
arr2 = np.random.randint(0,100,10)

In [18]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [20]:
arr.max()

95

In [22]:
arr.shape

(10,)

In [23]:
arr.argmax()

0

In [24]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [25]:
mat = np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
row = 0
col = 1

In [28]:
mat[row,col]

1

In [30]:
mat[5,7]

57